### ISSUE TITLE
Brace block on same line breaks PythonBraces

### ISSUE THREAD

**Issue by 88Alex** [JohnBish/python-braces#1]
For instance, this code:
`def main() { print("Hello, World!) }`
Should be interpreted as:
`def main():
    print("Hello, World!")`
But this does not work as intended, producing invalid Python code.

**Comment by JohnBish** [comment]
That's because you didn't close the string

**Comment by JohnBish** [comment]
Jk. I noticed that too. Should work now. Let me know if you manage to break it.
